# Generated by Django 5.1.6 on 2025-03-20 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0005_remove_urun_hesaplama_hesaplamalar_urunler_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hesaplamalar',
            name='email',
            field=models.EmailField(default='guest@example.com', help_text='Hesaplama yapan kullanıcının email adresi', max_length=254),
        ),
        migrations.AlterField(
            model_name='hesaplamalar',
            name='kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hesaplamalar', to=settings.AUTH_USER_MODEL),
        ),
    ]
