# Generated by Django 5.1.6 on 2025-04-22 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0016_alter_kategoriyolu_ad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HesaplamaDesiKgGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('en', models.FloatField()),
                ('boy', models.FloatField()),
                ('yukseklik', models.FloatField()),
                ('net_agirlik', models.FloatField()),
                ('desi_kg', models.FloatField()),
                ('hesaplama_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desi/Kg Hesaplama Geçmişi',
                'verbose_name_plural': 'Desi/Kg Hesaplama Geçmişleri',
            },
        ),
    ]
