# Generated by Django 5.1.6 on 2025-03-18 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='AltKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_kategori_adi', models.CharField(max_length=255)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='hesaplama.kategori')),
            ],
            options={
                'verbose_name': 'Alt Kategori',
                'verbose_name_plural': 'Alt Kategoriler',
                'unique_together': {('kategori', 'alt_kategori_adi')},
            },
        ),
        migrations.CreateModel(
            name='UrunGrubu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_grubu_adi', models.CharField(max_length=255)),
                ('alt_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urun_gruplari', to='hesaplama.altkategori')),
            ],
            options={
                'verbose_name': 'Ürün Grubu',
                'verbose_name_plural': 'Ürün Grupları',
                'unique_together': {('alt_kategori', 'urun_grubu_adi')},
            },
        ),
        migrations.CreateModel(
            name='KomisyonOrani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komisyon_orani', models.DecimalField(decimal_places=2, help_text='Komisyon oranı (% olarak)', max_digits=5)),
                ('urun_grubu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komisyon_oranlari', to='hesaplama.urungrubu')),
            ],
            options={
                'verbose_name': 'Komisyon Oranı',
                'verbose_name_plural': 'Komisyon Oranları',
            },
        ),
    ]
