# Generated by Django 5.1.6 on 2025-03-19 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0002_kategori_altkategori_urungrubu_komisyonorani'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
        migrations.CreateModel(
            name='PriceCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packaging_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desired_profit_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('desi', models.FloatField()),
                ('cargo_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hesaplama.kargofirma')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hesaplama.urungrubu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiyat Hesaplama',
                'verbose_name_plural': 'Fiyat Hesaplamalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
