# Generated by Django 5.1.6 on 2025-03-19 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0004_remove_pricecalculation_cargo_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='hesaplama',
        ),
        migrations.CreateModel(
            name='Hesaplamalar',
            fields=[
                ('hesaplama_id', models.AutoField(primary_key=True, serialize=False)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hesaplamalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hesaplama',
                'verbose_name_plural': 'Hesaplamalar',
            },
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('urun_id', models.AutoField(primary_key=True, serialize=False)),
                ('urun_ismi', models.CharField(max_length=100)),
                ('urun_maliyeti', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paketleme_maliyeti', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trendyol_hizmet_bedeli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kargo_firmasi', models.CharField(max_length=50)),
                ('kargo_ucreti', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stopaj_degeri', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desi_kg_degeri', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urun_kategorisi', models.TextField()),
                ('komisyon_orani', models.DecimalField(decimal_places=2, max_digits=5)),
                ('komisyon_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kdv_orani', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kar_orani', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kar_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('satis_fiyati_kdv_haric', models.DecimalField(decimal_places=2, max_digits=10)),
                ('satis_fiyati_kdv_dahil', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hesaplama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='hesaplama.hesaplamalar')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.DeleteModel(
            name='Hesaplama',
        ),
        migrations.DeleteModel(
            name='Urun',
        ),
    ]
