# Generated by Django 5.1.6 on 2025-03-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0006_hesaplamalar_email_alter_hesaplamalar_kullanici'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiyatBelirleme',
            fields=[
                ('urun_id', models.AutoField(primary_key=True, serialize=False)),
                ('urun_ismi', models.CharField(max_length=100)),
                ('urun_maliyeti', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paketleme_maliyeti', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trendyol_hizmet_bedeli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kargo_firmasi', models.CharField(max_length=50)),
                ('kargo_ucreti', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stopaj_degeri', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desi_kg_degeri', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urun_kategorisi', models.TextField()),
                ('komisyon_orani', models.DecimalField(decimal_places=2, max_digits=5)),
                ('komisyon_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kdv_orani', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kar_orani', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kar_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('satis_fiyati_kdv_haric', models.DecimalField(decimal_places=2, max_digits=10)),
                ('satis_fiyati_kdv_dahil', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hesaplama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiyat_belirlemeler', to='hesaplama.hesaplamalar')),
            ],
            options={
                'verbose_name': 'Fiyat Belirleme',
                'verbose_name_plural': 'Fiyat Belirlemeler',
            },
        ),
        migrations.DeleteModel(
            name='Urunler',
        ),
    ]
