# Generated by Django 5.1.6 on 2025-03-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0007_fiyatbelirleme_delete_urunler'),
    ]

    operations = [
        migrations.AddField(
            model_name='kargofirma',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='kargo_logo/'),
        ),
    ]
