# Generated by Django 5.1.6 on 2025-04-04 12:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0010_alter_desikgdeger_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HesaplamaPazaryeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(help_text='Pazar yerinin adı (Trendyol, Hepsiburada vb.)', max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True, help_text='Pazar yerinin aktif olup olmadığı')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, help_text='Kayıt oluşturulma tarihi')),
            ],
            options={
                'verbose_name': 'Hesaplama Pazar Yeri',
                'verbose_name_plural': 'Hesaplama Pazar Yerleri',
                'db_table': 'hesaplama_pazar_yeri',
            },
        ),
        migrations.CreateModel(
            name='HesaplamaKategoriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(help_text='Kategori adı', max_length=255)),
                ('seviye', models.IntegerField(help_text='Kategorinin seviyesi (1-4 arası)', validators=[django.core.validators.MinValueValidator(1)])),
                ('ust_kategori', models.ForeignKey(blank=True, help_text='Üst kategori referansı (hiyerarşi için)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='hesaplama.hesaplamakategoriler')),
            ],
            options={
                'verbose_name': 'Hesaplama Kategori',
                'verbose_name_plural': 'Hesaplama Kategoriler',
                'db_table': 'hesaplama_kategoriler',
            },
        ),
        migrations.CreateModel(
            name='HesaplamaKomisyonOranlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komisyon_orani', models.DecimalField(decimal_places=2, help_text='Komisyon oranı yüzdesi', max_digits=5)),
                ('gecerlilik_tarihi', models.DateField(help_text='Oranın geçerli olduğu tarih aralığı')),
                ('kategori_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komisyon_oranlari_seviye1', to='hesaplama.hesaplamakategoriler')),
                ('kategori_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komisyon_oranlari_seviye2', to='hesaplama.hesaplamakategoriler')),
                ('kategori_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komisyon_oranlari_seviye3', to='hesaplama.hesaplamakategoriler')),
                ('kategori_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komisyon_oranlari_seviye4', to='hesaplama.hesaplamakategoriler')),
                ('pazar_yeri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komisyon_oranlari', to='hesaplama.hesaplamapazaryeri')),
            ],
            options={
                'verbose_name': 'Hesaplama Komisyon Oranı',
                'verbose_name_plural': 'Hesaplama Komisyon Oranları',
                'db_table': 'hesaplama_komisyon_oranlari',
            },
        ),
        migrations.CreateModel(
            name='HesaplamaKategoriSeviyeleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maksimum_seviye', models.IntegerField(help_text='Pazar yerinin desteklediği en derin kategori seviyesi (1-4 arası)', validators=[django.core.validators.MinValueValidator(1)])),
                ('pazar_yeri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kategori_seviyesi', to='hesaplama.hesaplamapazaryeri')),
            ],
            options={
                'verbose_name': 'Hesaplama Kategori Seviyesi',
                'verbose_name_plural': 'Hesaplama Kategori Seviyeleri',
                'db_table': 'hesaplama_kategori_seviyeleri',
            },
        ),
    ]
