# Generated by Django 5.1.6 on 2025-04-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0012_alter_hesaplamakomisyonoranlari_pazar_yeri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesaplamakategoriler',
            name='pazar_yeri',
            field=models.ForeignKey(blank=True, help_text='Kategorinin ait olduğu pazar yeri', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategoriler', to='hesaplama.pazaryeri'),
        ),
    ]
