# Generated by Django 5.1.6 on 2025-04-22 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0013_hesaplamakategoriler_pazar_yeri'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriYolu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Kategori yolu adı', max_length=255)),
                ('komisyon_orani', models.DecimalField(decimal_places=2, help_text='Komisyon oranı yüzdesi', max_digits=5)),
                ('pazar_yeri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori_yollari', to='hesaplama.pazaryeri')),
                ('ust_kategori', models.ForeignKey(blank=True, help_text='Üst kategori yolu referansı', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='hesaplama.kategoriyolu')),
            ],
            options={
                'verbose_name': 'Kategori Yolu',
                'verbose_name_plural': 'Kategori Yolları',
                'db_table': 'kategori_yollari',
                'unique_together': {('pazar_yeri', 'ad')},
            },
        ),
    ]
