# Generated by Django 5.1.6 on 2025-04-24 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0017_hesaplamadesikggecmisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KargoUcretGecmis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('desi_kg_degeri', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yuvarlanmis_desi_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kargo_ucreti', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hesaplama_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kargo_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesaplama.kargofirma')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pazar_yeri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesaplama.pazaryeri')),
            ],
            options={
                'verbose_name': 'Kargo Ücreti Geçmişi',
                'verbose_name_plural': 'Kargo Ücreti Geçmişleri',
                'ordering': ['-hesaplama_tarihi'],
            },
        ),
    ]
