# Generated by Django 5.1.6 on 2025-04-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0021_alter_fiyathesaplamagecmisi_kullanici_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kargoucretgecmis',
            name='urun_ismi',
            field=models.CharField(default='Ürün', max_length=255),
        ),
    ]
