# Generated by Django 5.1.6 on 2025-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0024_fiyathesaplamagecmisi_urun_ismi'),
    ]

    operations = [
        migrations.AddField(
            model_name='komisyonoranigecmisi',
            name='urun_ismi',
            field=models.CharField(default='Ürün', max_length=255),
        ),
    ]
